/** Display names in CM Scout Intrinsic `DataService.Attributes` order (48). */
export const CM_SCOUT_ATTR_LABELS: string[] = [
  'Anticipation',
  'Creativity',
  'Crossing',
  'Decisions',
  'Dribbling',
  'Finishing',
  'Heading',
  'Long shots',
  'Marking',
  'Off the ball',
  'Passing',
  'Penalties',
  'Positioning',
  'Tackling',
  'Throw ins',
  'Handling',
  'One on ones',
  'Reflexes',
  'Acceleration',
  'Agility',
  'Balance',
  'Corners',
  'Flair',
  'Injury proneness',
  'Jumping',
  'Natural fitness',
  'Pace',
  'Set pieces',
  'Stamina',
  'Strength',
  'Technique',
  'Work rate',
  'Adaptability',
  'Aggression',
  'Ambition',
  'Bravery',
  'Consistency',
  'Determination',
  'Dirtiness',
  'Important matches',
  'Influence',
  'Loyalty',
  'Pressure',
  'Professionalism',
  'Sportsmanship',
  'Teamwork',
  'Temperament',
  'Versatility',
]
