/** ISO 3166-1 alpha-2 → regional indicator flag emoji. */
export function isoCountryCodeToFlag(iso: string): string {
  const cc = iso.trim().toUpperCase()
  if (!/^[A-Z]{2}$/.test(cc)) return ''
  const base = 0x1f1e6
  return [...cc].map((c) => String.fromCodePoint(base + c.charCodeAt(0) - 65)).join('')
}

/** CM nation.dat display names → ISO code for flag emoji (UK uses GB). */
const NATION_NAME_TO_ISO: Record<string, string> = {
  Afghanistan: 'AF',
  Albania: 'AL',
  Algeria: 'DZ',
  Andorra: 'AD',
  Angola: 'AO',
  Argentina: 'AR',
  Armenia: 'AM',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Bahrain: 'BH',
  Belarus: 'BY',
  Belgium: 'BE',
  Benin: 'BJ',
  Bolivia: 'BO',
  'Bosnia and Herzegovina': 'BA',
  Brazil: 'BR',
  Bulgaria: 'BG',
  Burkina: 'BF',
  'Burkina Faso': 'BF',
  Burundi: 'BI',
  Cameroon: 'CM',
  Canada: 'CA',
  Chile: 'CL',
  China: 'CN',
  Colombia: 'CO',
  'Costa Rica': 'CR',
  Croatia: 'HR',
  Cuba: 'CU',
  Cyprus: 'CY',
  'Czech Republic': 'CZ',
  Denmark: 'DK',
  Ecuador: 'EC',
  Egypt: 'EG',
  England: 'GB',
  Estonia: 'EE',
  Ethiopia: 'ET',
  Finland: 'FI',
  France: 'FR',
  Gabon: 'GA',
  Georgia: 'GE',
  Germany: 'DE',
  Ghana: 'GH',
  Greece: 'GR',
  Guatemala: 'GT',
  Honduras: 'HN',
  Holland: 'NL',
  Hungary: 'HU',
  Iceland: 'IS',
  India: 'IN',
  Indonesia: 'ID',
  Iran: 'IR',
  Iraq: 'IQ',
  Ireland: 'IE',
  Israel: 'IL',
  Italy: 'IT',
  'Ivory Coast': 'CI',
  Jamaica: 'JM',
  Japan: 'JP',
  Jordan: 'JO',
  Kazakhstan: 'KZ',
  Kenya: 'KE',
  Kuwait: 'KW',
  Latvia: 'LV',
  Lebanon: 'LB',
  Libya: 'LY',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Malaysia: 'MY',
  Mali: 'ML',
  Malta: 'MT',
  Mexico: 'MX',
  Moldova: 'MD',
  Montenegro: 'ME',
  Morocco: 'MA',
  Netherlands: 'NL',
  'New Zealand': 'NZ',
  Nicaragua: 'NI',
  Nigeria: 'NG',
  'Northern Ireland': 'GB',
  Norway: 'NO',
  Oman: 'OM',
  Pakistan: 'PK',
  Panama: 'PA',
  Paraguay: 'PY',
  Peru: 'PE',
  Philippines: 'PH',
  Poland: 'PL',
  Portugal: 'PT',
  Qatar: 'QA',
  Romania: 'RO',
  Russia: 'RU',
  'San Marino': 'SM',
  'Saudi Arabia': 'SA',
  Scotland: 'GB',
  Senegal: 'SN',
  Serbia: 'RS',
  Singapore: 'SG',
  Slovakia: 'SK',
  Slovenia: 'SI',
  'South Africa': 'ZA',
  'South Korea': 'KR',
  Spain: 'ES',
  Sweden: 'SE',
  Switzerland: 'CH',
  Syria: 'SY',
  Thailand: 'TH',
  Togo: 'TG',
  Trinidad: 'TT',
  Tunisia: 'TN',
  Turkey: 'TR',
  Ukraine: 'UA',
  'United Arab Emirates': 'AE',
  'United States': 'US',
  Uruguay: 'UY',
  USA: 'US',
  Venezuela: 'VE',
  Vietnam: 'VN',
  Wales: 'GB',
  Yemen: 'YE',
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
  Congo: 'CG',
  'Congo DR': 'CD',
  'Democratic Republic of Congo': 'CD',
  'Republic of Ireland': 'IE',
}

export function nationNameToFlagEmoji(nationName: string): string {
  const key = nationName.trim()
  if (!key) return ''
  const iso = NATION_NAME_TO_ISO[key] ?? NATION_NAME_TO_ISO[key.replace(/\s+/g, ' ')]
  if (!iso) return ''
  return isoCountryCodeToFlag(iso)
}

/** Split `Italy / Argentina` style display into nation labels. */
export function splitNationDisplay(nationDisplay: string): string[] {
  return nationDisplay
    .split('/')
    .map((s) => s.trim())
    .filter(Boolean)
}
